# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_soin', models.CharField(max_length=100)),
                ('type_soin', models.CharField(max_length=100)),
                ('adresse_soin', models.CharField(max_length=100)),
                ('frequence_soin', models.CharField(max_length=100)),
                ('ponctualite_definie', models.CharField(max_length=100)),
            ],
        ),
    ]
