# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prenom', models.CharField(default='', max_length=100)),
                ('adresse', models.CharField(default='', max_length=100)),
                ('telephone', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='soin',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='soins_app.Patient'),
        ),
    ]
