# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='type_soin',
            field=models.CharField(choices=[('SC', 'Soin courant'), ('SS', 'Soin Spécifique'), ('SID', 'Soin infirmier à domicile')], max_length=2),
        ),
    ]
