# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0002_auto_20171212_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soin',
            name='adresse_soin',
        ),
    ]
