# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0003_remove_soin_adresse_soin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='frequence_soin',
            field=models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=2),
        ),
    ]
