# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0004_remove_soin_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='soin',
            name='patient',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='soins_app.Patient'),
            preserve_default=False,
        ),
    ]
