# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0005_auto_20171212_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='frequence_soin',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=2),
        ),
    ]
