# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0006_auto_20171224_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soin',
            name='ponctualite_definie',
        ),
    ]
