# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0007_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='soin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soins_app.Soin'),
        ),
    ]
