# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0010_remove_visit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='nurse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infirmiers_app.Nurse'),
        ),
    ]
