# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-13 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0011_auto_20171213_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soins_app.Patient'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infirmiers_app.Nurse'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='soin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soins_app.Soin'),
        ),
    ]
