# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 08:13
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0012_auto_20171213_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='frequence_soin',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=2),
        ),
    ]
