# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 16:22
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0013_auto_20171214_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='frequence_soin',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=2),
        ),
    ]
