# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0014_auto_20171214_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Office',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
