# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0015_patient_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='patient',
            field=models.IntegerField(default=1),
        ),
    ]
