# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0016_auto_20171215_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='patient',
            field=models.IntegerField(),
        ),
    ]
