# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soins_app', '0017_auto_20171215_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soin',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
