# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
