# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0003_auto_20171218_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
