# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0005_auto_20171222_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soin',
            name='strict_punctuality',
        ),
        migrations.AddField(
            model_name='soin',
            name='specific_visit_time',
            field=models.TimeField(null=True),
        ),
    ]
