# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0008_auto_20180105_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soin',
            old_name='nom_soin',
            new_name='name_soin',
        ),
    ]
