# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0009_auto_20180105_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Adress',
            new_name='Address',
        ),
    ]
