# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0010_auto_20180111_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soin',
            name='type_soin',
            field=models.CharField(choices=[('CT', 'Common treatment'), ('ST', 'Specific Treatment'), ('ET', 'Exceptional Treatment')], max_length=2),
        ),
    ]
