# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infirmiers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='Office',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
