# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 21:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('Su', 'Sunday')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(95)])),
                ('end_time', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(96)])),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('PhoneNumber', models.IntegerField()),
                ('availableDays', models.ManyToManyField(to='nurses_app.AvailableDay')),
            ],
        ),
        migrations.AddField(
            model_name='availableday',
            name='intervals',
            field=models.ManyToManyField(to='nurses_app.Interval'),
        ),
    ]
