# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='PhoneNumber',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='interval',
            unique_together=set([('start_time', 'end_time')]),
        ),
    ]
