# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurses_app', '0002_nurse_office'),
        ('nurses_app', '0002_auto_20171208_1602'),
    ]

    operations = [
    ]
