# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses_app', '0005_auto_20171215_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='PhoneNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
