# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses_app', '0006_auto_20171222_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=2, null=True),
        ),
    ]
