# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurses_app', '0007_auto_20180114_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='weekday',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('Su', 'Sunday')], max_length=2, null=True),
        ),
    ]
